# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nome')),
                ('age', models.CharField(default=None, max_length=255, verbose_name='Idade')),
                ('email', models.CharField(default=None, max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(default=None, max_length=255, verbose_name='Telefone')),
                ('inmate', models.BooleanField(default=False, verbose_name='Internado')),
                ('hospital_name', models.CharField(default=None, max_length=255, verbose_name='Nome do Hospital')),
                ('hospital_contact', models.CharField(default=None, max_length=255, verbose_name='Contato do Hospital')),
                ('medical_approved', models.BooleanField(default=False, verbose_name='Aprovação Médica')),
                ('parental_approved', models.CharField(default=None, max_length=255, verbose_name='Aprovação do Responsável')),
                ('description', models.TextField(default=None, verbose_name='Descrição')),
                ('hospital_address', models.CharField(default=None, max_length=255, verbose_name='Endereço do Hospital')),
                ('observation', models.CharField(default=None, max_length=255, verbose_name='Observação')),
                ('liason', models.TextField(default=None, verbose_name='Relacionamento com Paciente')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('inviavel', 'Inviavel'), ('pre_aprovado', 'Pré-Aprovado')], max_length=1, verbose_name='Status')),
                ('planning_description', models.TextField(default=None, verbose_name='Descrição do Planejamento')),
            ],
        ),
    ]
