# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dream',
            options={'verbose_name_plural': 'Sonhos'},
        ),
        migrations.AlterField(
            model_name='dream',
            name='liason',
            field=models.CharField(default=None, max_length=255, verbose_name='Relacionamento com Paciente'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='observation',
            field=models.TextField(default=None, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='parental_approved',
            field=models.BooleanField(default=False, verbose_name='Aprovação do Responsável'),
        ),
    ]
