# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170831_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='age',
            field=models.CharField(default=None, max_length=255, verbose_name='Idade do Paciente'),
        ),
    ]
