# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170831_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Endereço do Paciente'),
        ),
    ]
