# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170831_1948'),
        ('api', '0005_dream_address'),
    ]

    operations = [
    ]
