# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170901_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='dream_report',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='observation',
        ),
        migrations.AlterField(
            model_name='dream',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Endereço do Local de Internação'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='age',
            field=models.CharField(default=None, max_length=255, verbose_name='Idade do Sonhador'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Nome do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='description',
            field=models.TextField(default=None, verbose_name='Descrição Detalhada do sonho'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='email',
            field=models.CharField(default=None, max_length=255, verbose_name='E-mail do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='health_conditions',
            field=models.TextField(default=None, verbose_name='Condições Médicas e Expectativa de Vida'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='hospital_contact',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Telefone do Contato do Local de Internação'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='hospital_name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Local de Internação'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='inmate',
            field=models.BooleanField(default=False, verbose_name='Está Internado?'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='liason',
            field=models.CharField(default=None, max_length=255, verbose_name='Relacionamento com Sonhador (Ex. filho, cuidador)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='medical_approved',
            field=models.BooleanField(default=False, verbose_name='Tem Aprovação Médica para a Realização do Sonho?'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Nome do Sonhador'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='parental_approved',
            field=models.BooleanField(default=False, verbose_name='Tem Aprovação do Responsável para a Realização do Sonho?'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='phone',
            field=models.CharField(default=None, max_length=255, verbose_name='Telefone do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='planning_description',
            field=models.TextField(default=None, verbose_name='Planejamento do Sonho'),
        ),
    ]
