# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170901_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nome')),
                ('nickname', models.CharField(default=None, max_length=255, verbose_name='Apelido')),
                ('birthdate', models.DateField(default=None, verbose_name='Data de nascimento')),
                ('telephone', models.CharField(default=None, max_length=255, verbose_name='Telefone')),
                ('cellphone', models.CharField(default=None, max_length=255, verbose_name='Celular')),
                ('email', models.CharField(default=None, max_length=255, verbose_name='Email')),
                ('address', models.CharField(default=None, max_length=255, verbose_name='Endereço ')),
                ('personal_characteristics', models.TextField(default=None, verbose_name='Características pessoais')),
                ('talents', models.TextField(default=None, verbose_name='Talentos')),
                ('available_days_times', models.CharField(choices=[('seg-manha', 'Segunda - Manhã'), ('seg-tarde', 'Segunda - Tarde'), ('seg-noite', 'Segunda - Noite'), ('ter-manha', 'Terça - Manhã'), ('ter-tarde', 'Terça - Tarde'), ('ter-noite', 'Terça - Noite'), ('qua-manha', 'Quarta - Manhã'), ('qua-tarde', 'Quarta - Tarde'), ('qua-noite', 'Quarta - Noite'), ('qui-manha', 'Quinta - Manhã'), ('qui-tarde', 'Quinta - Tarde'), ('qui-noite', 'Quinta - Noite'), ('sex-manha', 'Sexta - Manhã'), ('sex-tarde', 'Sexta - Tarde'), ('sex-noite', 'Sexta - Noite'), ('sab-manha', 'Sábado - Manhã'), ('sab-tarde', 'Sábado - Tarde'), ('sab-noite', 'Sábado - Noite'), ('dom-manha', 'Domingo - Manhã'), ('dom-tarde', 'Domingo - Tarde'), ('dom-noite', 'Domingo - Noite')], max_length=20, verbose_name='Designação do voluntário ')),
                ('assignment', models.CharField(choices=[('hunter', 'Hunter'), ('farm', 'Farm'), ('reg', 'REG')], max_length=20, verbose_name='Designação do voluntário ')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default=None, max_length=20, verbose_name='Designação do voluntário ')),
            ],
        ),
    ]
