# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDaysTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado'), ('dom', 'Domingo')], default=None, max_length=20, verbose_name='Dia da semana')),
                ('time', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default=None, max_length=20, verbose_name='Horário do dia')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_days_times',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='available_days_times',
            field=models.ManyToManyField(to='api.AvailableDaysTimes'),
        ),
    ]
