# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170901_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='dream',
            old_name='liason',
            new_name='contact_liason',
        ),
        migrations.RenameField(
            model_name='dream',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='dream',
            old_name='age',
            new_name='dreamer_age',
        ),
        migrations.RenameField(
            model_name='dream',
            old_name='health_conditions',
            new_name='dreamer_health_conditions',
        ),
        migrations.RenameField(
            model_name='dream',
            old_name='name',
            new_name='dreamer_name',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='hospital_contact',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='dream',
            name='category',
            field=models.CharField(choices=[('sonho_ir', 'Sonho Ir'), ('sonho_fazer', 'Sonho Fazer'), ('sonho_conhecer_rever', 'Sonho Conhecer / Rever')], default='', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='dream',
            name='dreamer_address',
            field=models.CharField(default=None, max_length=255, verbose_name='Endereço do Sonhador'),
        ),
        migrations.AddField(
            model_name='dream',
            name='local',
            field=models.CharField(default=None, max_length=255, verbose_name='Local de Internação'),
        ),
        migrations.AddField(
            model_name='dream',
            name='local_address',
            field=models.CharField(default=None, max_length=255, verbose_name='Endereço do Local de Internação'),
        ),
        migrations.AddField(
            model_name='dream',
            name='local_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Nome do Contato do Local de Internação'),
        ),
        migrations.AddField(
            model_name='dream',
            name='local_phone',
            field=models.CharField(default=None, max_length=255, verbose_name='Telefone do Contato do Local de Internação'),
        ),
    ]
