# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170901_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='category',
            field=models.CharField(choices=[('sonho_ir', 'Sonho Ir'), ('sonho_fazer', 'Sonho Fazer'), ('sonho_conhecer_rever', 'Sonho Conhecer / Rever')], default=None, max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='description',
            field=models.TextField(default=None, verbose_name='Descrição Detalhada do Sonho'),
        ),
    ]
