# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170901_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dream_needs',
            field=models.TextField(default=None, null=True, verbose_name='Necessidades do Sonho'),
        ),
    ]
