# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170901_1451'),
        ('api', '0013_auto_20170901_1500'),
    ]

    operations = [
    ]
