# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20170901_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabledaystimes',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='availabledaystimes',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordem na lista'),
        ),
    ]
