# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170901_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='needs_attended',
            field=models.TextField(default=None, null=True, verbose_name='Necessidades Atendidas'),
        ),
    ]
