# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabledaystimes',
            options={'ordering': ('order',), 'verbose_name_plural': 'Dias / Horários Disponíveis'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name_plural': 'Voluntários'},
        ),
        migrations.AddField(
            model_name='dream',
            name='doctor_contact',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Contato do médico'),
        ),
        migrations.AddField(
            model_name='dream',
            name='doctor_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Médico responsável'),
        ),
        migrations.AddField(
            model_name='dream',
            name='dream_short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Apelido do sonho (descrição curta)'),
        ),
        migrations.AddField(
            model_name='dream',
            name='dreamer_nickname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Apelido do sonhador'),
        ),
        migrations.AddField(
            model_name='dream',
            name='health_device_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descreva o dispositivo'),
        ),
        migrations.AddField(
            model_name='dream',
            name='how_did_know_us',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Como soube do trabalho da Rope'),
        ),
        migrations.AddField(
            model_name='dream',
            name='impediment_days',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Dias no qual o sonho não pode ser realizado (Dias de tratamento, etc)'),
        ),
        migrations.AddField(
            model_name='dream',
            name='linked_food',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Alimentação'),
        ),
        migrations.AddField(
            model_name='dream',
            name='linked_partners',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Parceiros'),
        ),
        migrations.AddField(
            model_name='dream',
            name='linked_transport',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Transporte'),
        ),
        migrations.AddField(
            model_name='dream',
            name='linked_volunteers',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Voluntários'),
        ),
        migrations.AddField(
            model_name='dream',
            name='mental_health',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Condição mental do sonhador'),
        ),
        migrations.AddField(
            model_name='dream',
            name='mobility',
            field=models.CharField(blank=True, choices=[('caminha_sozinho', 'Caminha sozinho'), ('caminha_auxiliado', 'Caminha com auxilio'), ('cadeira_rodas', 'Cadeira de rodas'), ('acamado', 'acamado')], default=None, max_length=255, null=True, verbose_name='Como é a mobilidade do sonhador?'),
        ),
        migrations.AddField(
            model_name='dream',
            name='observations',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Mais alguma informação importante (Restrição alimentar, autonomia pra ir ao banheiro, etc)'),
        ),
        migrations.AddField(
            model_name='dream',
            name='significative_days',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Data importante pro sonho, caso exista'),
        ),
        migrations.AddField(
            model_name='dream',
            name='special_care',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Cuidados especiais (banheiro, alimentação e locomoção)'),
        ),
        migrations.AddField(
            model_name='dream',
            name='spendings',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Valores gastos'),
        ),
        migrations.AddField(
            model_name='dream',
            name='uses_health_device',
            field=models.BooleanField(default=False, verbose_name='Sonhador usa algum dispositivo?'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='category',
            field=models.CharField(blank=True, choices=[('sonho_ir', 'Sonho Ir'), ('sonho_fazer', 'Sonho Fazer'), ('sonho_conhecer_rever', 'Sonho Conhecer / Rever')], default=None, max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='E-mail do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_liason',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Relacionamento com Sonhador (Ex. filho, cuidador)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Telefone do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição Detalhada do Sonho'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Endereço do Sonhador'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_age',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Idade do Sonhador'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_health_conditions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Condições Médicas e Expectativa de Vida'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome do Sonhador'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='status',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('inviavel', 'Inviavel'), ('aprovado', 'Aprovado')], default='novo', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default=None, max_length=20, verbose_name='Status '),
        ),
    ]
