# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabledaystimes',
            options={'ordering': ('order',), 'verbose_name_plural': 'Dias / Horários Disponíveis'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name_plural': 'Voluntários'},
        ),
        migrations.AlterField(
            model_name='dream',
            name='category',
            field=models.CharField(blank=True, choices=[('sonho_ir', 'Sonho Ir'), ('sonho_fazer', 'Sonho Fazer'), ('sonho_conhecer_rever', 'Sonho Conhecer / Rever')], default=None, max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='E-mail do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_liason',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Relacionamento com Sonhador (Ex. filho, cuidador)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='contact_phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Telefone do Contato'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição Detalhada do Sonho'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Endereço do Sonhador'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_age',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Idade do Sonhador'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_health_conditions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Condições Médicas e Expectativa de Vida'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dreamer_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome do Sonhador'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default=None, max_length=20, verbose_name='Status '),
        ),
    ]
