# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170904_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='dream_nickname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Apelido do sonho'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição rápida do sonho para página aberta'),
        ),
    ]
