# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170904_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Endereço '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cellphone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome do contato'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='document',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='help_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição da ajuda'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='observation',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Observações (Especificar doação)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default=None, max_length=20, null=True, verbose_name='Designação do voluntário '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Endereço '),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='assignment',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('farm', 'Farm'), ('reg', 'REG')], max_length=20, null=True, verbose_name='Designação do voluntário '),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cellphone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='personal_characteristics',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Características pessoais'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default=None, max_length=20, null=True, verbose_name='Status '),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='talents',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Talentos'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
