# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170904_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='category',
            field=models.CharField(blank=True, choices=[('sonho_ir', 'Sonho Ir'), ('sonho_fazer', 'Sonho Fazer'), ('sonho_conhecer_rever', 'Sonho Conhecer / Rever')], default='sonho_ir', max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='mobility',
            field=models.CharField(blank=True, choices=[('caminha_sozinho', 'Caminha sozinho'), ('caminha_auxiliado', 'Caminha com auxilio'), ('cadeira_rodas', 'Cadeira de rodas'), ('acamado', 'acamado')], default='caminha_sozinho', max_length=255, null=True, verbose_name='Como é a mobilidade do sonhador?'),
        ),
    ]
