# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170904_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dream_needs',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Necessidades do Sonho (Esse campo será publicado)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_nickname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Apelido do sonho (Esse campo será publicado)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição rápida do sonho para página aberta (Esse campo será publicado)'),
        ),
    ]
