# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20170904_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='linked_partners',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='api.Partner'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='linked_volunteers',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='api.Volunteer'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='status',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('inviavel', 'Inviavel'), ('aprovado', 'Aprovado'), ('realizado', 'Realizado')], default='novo', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
