# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20170904_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='linked_partners',
            field=models.ManyToManyField(blank=True, related_name='_dream_linked_partners_+', to='api.Partner'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='linked_volunteers',
            field=models.ManyToManyField(blank=True, related_name='_dream_linked_volunteers_+', to='api.Volunteer'),
        ),
    ]
