# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170904_1152'),
        ('api', '0026_auto_20170904_1715'),
    ]

    operations = [
    ]
