# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20170905_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome da empresa (PJ)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='category',
            field=models.CharField(blank=True, choices=[('sonho_ir', 'Sonho Ir'), ('sonho_fazer', 'Sonho Fazer'), ('sonho_conhecer_rever', 'Sonho Conhecer / Rever')], default='sonho_ir', max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='status',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('inviavel', 'Inviável'), ('aprovado', 'Aprovado'), ('viabilizado', 'Viabilizado'), ('realizado', 'Realizado')], default='novo', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='document',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Documento (CPF/CNPJ)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='novo', max_length=20, null=True, verbose_name='Status '),
        ),
    ]
