# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20170905_1130'),
        ('api', '0028_auto_20170905_1128'),
    ]

    operations = [
    ]
