# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20170905_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='document_type',
            field=models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=20, verbose_name='Tipo de pessoa'),
        ),
    ]
