# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170904_1727'),
        ('api', '0030_auto_20170905_1135'),
    ]

    operations = [
    ]
