# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20170905_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AlterField(
            model_name='partner',
            name='available_days_times',
            field=models.ManyToManyField(blank=True, to='api.AvailableDaysTimes'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='service_help',
            field=models.BooleanField(default=False, verbose_name='Ajuda com serviço?'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='available_days_times',
            field=models.ManyToManyField(blank=True, to='api.AvailableDaysTimes'),
        ),
    ]
